In [1]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import MinMaxScaler

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import top_k_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

In [3]:

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [4]:
from itertools import combinations

In [5]:
import seaborn as sns
sns.set_style("whitegrid")

In [6]:
import random 

In [7]:
noun_prhases_new_data_with_national_filter = pd.read_csv('noun_phrases_new_data_with_filters.csv')

In [8]:
noun_prhases_new_data_with_national_filter

Unnamed: 0          noun_sentence state  count      mean  variance  \
0                0   % efficiency furnace    TX    NaN       NaN       NaN   
1                1          % energy star    TX    NaN       NaN       NaN   
2                2                 % loan    TX    NaN       NaN       NaN   
3                3       % purchase price    TX    NaN       NaN       NaN   
4                4                 % usda    TX    NaN       NaN       NaN   
...            ...                    ...   ...    ...       ...       ...   
263539      263539        zero entry pool    SC    NaN       NaN       NaN   
263540      263540    zero+ mortgage plan    SC   14.0 -0.021060  0.002199   
263541      263541        zone irrigation    SC    8.0 -0.018282  0.009964   
263542      263542  zone sprinkler system    SC    NaN       NaN       NaN   
263543      263543            zoo atlanta    SC    NaN       NaN       NaN   

            noun_sentence_USA state_USA  count_USA  mean_USA  ...  \
0        % efficiency furnace       USA      240.0  0.027267  ...   
1               % energy star       USA        9.0 -0.028088  ...   
2                      % loan       USA       60.0  0.005112  ...   
3            % purchase price       USA      202.0 -0.022110  ...   
4                      % usda       USA      954.0  0.013769  ...   
...                       ...       ...        ...       ...  ...   
263539        zero entry pool       USA       18.0  0.052362  ...   
263540    zero+ mortgage plan       USA       14.0 -0.021060  ...   
263541        zone irrigation       USA        8.0 -0.018282  ...   
263542  zone sprinkler system       USA      256.0  0.042055  ...   
263543            zoo atlanta       USA      235.0  0.006908  ...   

        Filter_N100_Error1.5%_2.00_USA  Filter_N100_Error1.5%_1.00_USA  \
0                                    0                               0   
1                                    0                               0   
2                                    0                               0   
3                                    0                               0   
4                                    0                               0   
...                                ...                             ...   
263539                               0                               0   
263540                               0                               0   
263541                               0                               0   
263542                               0                               0   
263543                               0                               0   

        Filter_N100_Error1.5%_0.50_USA  stdev/mean  \
0                                    0         NaN   
1                                    0         NaN   
2                                    0         NaN   
3                                    0         NaN   
4                                    0         NaN   
...                                ...         ...   
263539                               0         NaN   
263540                               0    2.226868   
263541                               0    5.459877   
263542                               0         NaN   
263543                               0         NaN   

        Filter_N100_Error1.5%_state  Filter_N100_Error1.5%_3.33_state  \
0                                 0                                 0   
1                                 0                                 0   
2                                 0                                 0   
3                                 0                                 0   
4                                 0                                 0   
...                             ...                               ...   
263539                            0                                 0   
263540                            0                                 0   
263541                            0            

In [9]:
noun_sentences_by_listingid = pd.read_csv('ch_noun_sentences_by_listingid_CJ_2_full.csv')

In [10]:
noun_sentences_by_listingid

Unnamed: 0    index               noun_sentence  listingid state
0                  0        0           main level boasts       4002    KS
1                  1        1              walk-in pantry       4002    KS
2                  2        2             enormous closet       4002    KS
3                  3        3        huge recreation room       4002    KS
4                  4        4  stainless steel appliances       4002    KS
...              ...      ...                         ...        ...   ...
19491522    19491522  3604933                 canyon lake  290220824    TX
19491523    19491523  3604934                  floor plan  290220824    TX
19491524    19491524  3604935                 shade trees  290221239    TX
19491525    19491525  3604936                    new deck  290221239    TX
19491526    19491526  3604937                  large yard  290221239    TX

[19491527 rows x 5 columns]

In [11]:
state = 'GA'

In [12]:
'''

'''

file = 'NEW_AVM_DATA'+state+'_full.fea'
noun_avm_data = pd.read_feather(file)

In [13]:
noun_avm_data

index  listingid  asgpropid       qtr       avmvalue cbsa_div  \
0           338  220005293   25704362  202008.0  519120.957891    12060   
1           339  201184809   25705719  201908.0  280979.800818    12060   
2           340  236831405   25705804  202102.0  299548.162298    12060   
3           341  231029170   25720078  202011.0  354959.881618    12060   
4           342  234567556   25720214  202102.0  382737.269635    12060   
...         ...        ...        ...       ...            ...      ...   
450698  3670112  185648594   26226431  201811.0  246024.269713    12060   
450699  3670113  218275542   26227794  202002.0  266431.127358    12060   
450700  3670114  227630548   26227794  202011.0  290204.899310    12060   
450701  3670115  227628311   26227794  202011.0  290204.899310    12060   
450702  3670116  227393703   26228018  202008.0  251178.454360    12060   

         cbsa state    Zip fips_Code  ... story  effective_year_built  \
0       12060    GA  30014     13297  ...   1.0                2003.0   
1       12060    GA  30014     13297  ...   1.0                2000.0   
2       12060    GA  30014     13297  ...   1.0                2006.0   
3       12060    GA  30014     13297  ...   2.0                2016.0   
4       12060    GA  30014     13297  ...   1.0                2017.0   
...       ...   ...    ...       ...  ...   ...                   ...   
450698  12060    GA  30066     13067  ...   2.0                1971.0   
450699  12060    GA  30066     13067  ...   1.0                2020.0   
450700  12060    GA  30066     13067  ...   1.0                2020.0   
450701  12060    GA  30066     13067  ...   1.0                2020.0   
450702  12060    GA  30066     13067  ...   1.0                1973.0   

         transdate transprice  bedrooms  cj_living_area  \
0       2020-09-03   390000.0       NaN          3090.0   
1       2019-07-15   320000.0       NaN          2838.0   
2       2021-03-26   330000.0       NaN          2256.0   
3       2020-12-07   349900.0       NaN          2996.0   
4       2021-02-25   373000.0       NaN          2560.0   
...            ...        ...       ...             ...   
450698  2018-12-07   255000.0       3.0          2230.0   
450699  2020-03-10   200000.0       3.0          2220.0   
450700  2020-10-16   289900.0       3.0          2220.0   
450701  2020-10-16   289900.0       3.0          2220.0   
450702  2020-08-07   243000.0       3.0          1634.0   

                                            publicremarks listingPrice  \
0       New and Improved Price! Such elegance and opul...     450000.0   
1       Perfect Home for Large Family, In-laws, Roomma...     324900.0   
2       Sitting on a spacious two acres, this beautifu...     325000.0   
3       This beautiful 6 bedroom, 3 bathroom home has ...     359000.0   
4       New Listing ! 4 Bdrm/3 full Bath- Willows @ Cr...     369900.0   
...                                                   ...          ...   
450698  IF YOU ARE LOOKING FOR A MOVE-IN READY HOME WI...     285000.0   
450699  Sweet home with mid-century feel! This ranch w...     205000.0   
450700  Amazing Ranch style home with great renovation...     289900.0   
450701  Amazing Ranch style home with great renovation...     289900.0   
450702  NEW PRICE!! Great opportunity in E Cobb - Spra...     250000.0   

        avmerror  rentsale  
0      -0.331079         S  
1       0.121938         S  
2       0.092278         S  
3      -0.014461         S  
4      -0.026105         S  
...          ...       ...  
450698  0.035199         S  
450699 -0.332156         S  
450700 -0.001052         S  
450701 -0.001052         S  
450702 -0.033656         S  

[450703 rows x 21 columns]

In [14]:
noun_avm_data = noun_avm_data.set_index('listingid')

In [15]:
noun_avm_data

index  asgpropid       qtr       avmvalue cbsa_div   cbsa state  \
listingid                                                                      
220005293      338   25704362  202008.0  519120.957891    12060  12060    GA   
201184809      339   25705719  201908.0  280979.800818    12060  12060    GA   
236831405      340   25705804  202102.0  299548.162298    12060  12060    GA   
231029170      341   25720078  202011.0  354959.881618    12060  12060    GA   
234567556      342   25720214  202102.0  382737.269635    12060  12060    GA   
...            ...        ...       ...            ...      ...    ...   ...   
185648594  3670112   26226431  201811.0  246024.269713    12060  12060    GA   
218275542  3670113   26227794  202002.0  266431.127358    12060  12060    GA   
227630548  3670114   26227794  202011.0  290204.899310    12060  12060    GA   
227628311  3670115   26227794  202011.0  290204.899310    12060  12060    GA   
227393703  3670116   26228018  202008.0  251178.454360    12060  12060    GA   

             Zip fips_Code census_tract  story  effective_year_built  \
listingid                                                              
220005293  30014     13297  13297110602    1.0                2003.0   
201184809  30014     13297  13297110602    1.0                2000.0   
236831405  30014     13297  13297110602    1.0                2006.0   
231029170  30014     13297  13297110602    2.0                2016.0   
234567556  30014     13297  13297110602    1.0                2017.0   
...          ...       ...          ...    ...                   ...   
185648594  30066     13067  13067030313    2.0                1971.0   
218275542  30066     13067  13067030313    1.0                2020.0   
227630548  30066     13067  13067030313    1.0                2020.0   
227628311  30066     13067  13067030313    1.0                2020.0   
227393703  30066     13067  13067030313    1.0                1973.0   

            transdate  transprice  bedrooms  cj_living_area  \
listingid                                                     
220005293  2020-09-03    390000.0       NaN          3090.0   
201184809  2019-07-15    320000.0       NaN          2838.0   
236831405  2021-03-26    330000.0       NaN          2256.0   
231029170  2020-12-07    349900.0       NaN          2996.0   
234567556  2021-02-25    373000.0       NaN          2560.0   
...               ...         ...       ...             ...   
185648594  2018-12-07    255000.0       3.0          2230.0   
218275542  2020-03-10    200000.0       3.0          2220.0   
227630548  2020-10-16    289900.0       3.0          2220.0   
227628311  2020-10-16    289900.0       3.0          2220.0   
227393703  2020-08-07    243000.0       3.0          1634.0   

                                               publicremarks  listingPrice  \
listingid                                                                    
220005293  New and Improved Price! Such elegance and opul...      450000.0   
201184809  Perfect Home for Large Family, In-laws, Roomma...      324900.0   
236831405  Sitting on a spacious two acres, this beautifu...      325000.0   
231029170  This beautiful 6 bedroom, 3 bathroom home has ...      359000.0   
234567556  New Listing ! 4 Bdrm/3 full Bath- Willows @ Cr...      369900.0   
...                                                      ...           ...   
185648594  IF YOU ARE LOOKING FOR A MOVE-IN READY HOME WI...      285000.0   
218275542  Sweet home with mid-century feel! This ranch w...      205000.0   
227630548  Amazing Ranch style home with great renovation...      289900.0   
227628311  Amazing Ranch style home with great renovation...      289900.0   
227393703  NEW PRICE!! Great opportunity in E Cobb - Spra...      250000.0   

           avmerror rentsale  
listingid                     
220005293 -0.331079        S  
201184809  0.121938        S  
236831405  0.092278        S  
231029170 -0.014461        S  
234567556 -0.0

In [16]:
file = 'new_avm_df__full_data_state_'+state+'_noun_sentences.fea'
noun_sentence_state = pd.read_feather(file)

In [17]:
noun_sentence_state

noun_sentence  count  AVM_Error  \
0                     exemplary execution symmetry      2   1.963612   
1                                indiana limestone      2   1.963612   
2                    gracious ensuite guest suites      1   0.981806   
3                          grand stair hall levels      2   1.963612   
4                            veritable masterpiece      2   1.963612   
...                                            ...    ...        ...   
1070329  excellent opportunity investors spec home      1 -24.172772   
1070330               runs road frontage lot 4046.      1 -24.172772   
1070331                     slab septic tank place      1 -24.172772   
1070332                    tennis courts boat ramp      1 -43.810721   
1070333                        easy access s. gate      1 -43.810721   

                                 AVM_Error_List  Listing_Error  \
0        [0.981805771850691, 0.981805771850691]      -0.159459   
1        [0.981805771850691, 0.981805771850691]      -0.159459   
2                           [0.981805771850691]      -0.079730   
3        [0.981805771850691, 0.981805771850691]      -0.159459   
4        [0.981805771850691, 0.981805771850691]      -0.159459   
...                                         ...            ...   
1070329                   [-24.172772060805634]      -2.020833   
1070330                   [-24.172772060805634]      -2.020833   
1070331                   [-24.172772060805634]      -2.020833   
1070332                    [-43.81072136924543]      -1.068966   
1070333                    [-43.81072136924543]      -1.068966   

                                   Listing_Error_List          Listingid_List  \
0        [-0.07972972972972973, -0.07972972972972973]  [237540444, 284886961]   
1        [-0.07972972972972973, -0.07972972972972973]  [237540444, 284886961]   
2                              [-0.07972972972972973]             [284886961]   
3        [-0.07972972972972973, -0.07972972972972973]  [237540444, 284886961]   
4        [-0.07972972972972973, -0.07972972972972973]  [237540444, 284886961]   
...                                               ...                     ...   
1070329                         [-2.0208333333333335]               [5037260]   
1070330                         [-2.0208333333333335]               [5037260]   
1070331                         [-2.0208333333333335]               [5037260]   
1070332                         [-1.0689655172413792]               [3873784]   
1070333                         [-1.0689655172413792]               [3873784]   

         AVM_Error_Average  Listing_Error_Average  \
0                 0.981806              -0.079730   
1                 0.981806              -0.079730   
2                 0.981806              -0.079730   
3                 0.981806              -0.079730   
4                 0.981806              -0.079730   
...                    ...                    ...   
1070329         -24.172772              -2.020833   
1070330         -24.172772              -2.020833   
1070331         -24.172772              -2.020833   
1070332         -43.810721              -1.068966   
1070333         -43.810721              -1.068966   

                                      AVM_Error_Indicators  \
0        [0.981805771850691, 0.0, 0.0, -3.0, 0.98180577...   
1        [0.981805771850691, 0.0, 0.0, -3.0, 0.98180577...   
2                                                       []   
3        [0.981805771850691, 0.0, 0.0, -3.0, 0.98180577...   
4        [0.981805771850691, 0.0, 0.0, -3.0, 0.98180577...   
...                                                    ...   
1070329                                                 []   
1070330                                                 []   
1070331                                                 []   
1070332                                                 []   
1070333                                                 []   

                        

In [18]:
for col in noun_sentence_state.columns:
    print(col)

noun_sentence
count
AVM_Error
AVM_Error_List
Listing_Error
Listing_Error_List
Listingid_List
AVM_Error_Average
Listing_Error_Average
AVM_Error_Indicators
Listing_Error_Indicators


In [19]:
noun_sentences_by_listingid_state = noun_sentences_by_listingid[noun_sentences_by_listingid['state']==state]

In [20]:
noun_sentences_by_listingid_state

Unnamed: 0    index      noun_sentence  listingid state
6464782     6464782        0        crawl space       1066    GA
6464783     6464783        1   ranch style home       1069    GA
6464784     6464784        2       bedroom plan       1069    GA
6464785     6464785        3     breakfast nook       1069    GA
6464786     6464786        4      gas fireplace       1069    GA
...             ...      ...                ...        ...   ...
8926336     8926336  2461554      new cabinetry  286497014    GA
8926337     8926337  2461555  marble backsplash  286497014    GA
8926338     8926338  2461556  high-end finishes  286497014    GA
8926339     8926339  2461557    open floor plan  286497014    GA
8926340     8926340  2461558      chefs kitchen  286497014    GA

[2461559 rows x 5 columns]

In [21]:
all_listingids = set(noun_sentences_by_listingid_state['listingid'].unique())

In [22]:
train_listingids = random.sample(all_listingids, int(70*len(all_listingids)/100))

In [23]:
test_listingids = all_listingids.difference(train_listingids)

In [24]:
len(test_listingids)+len(train_listingids)

434910

In [25]:
len(all_listingids)

434910

In [26]:
noun_prhases_new_data_with_national_filter_state = noun_prhases_new_data_with_national_filter\
                                                        [noun_prhases_new_data_with_national_filter['state']==state]

In [27]:
noun_prhases_new_data_with_national_filter_state = noun_prhases_new_data_with_national_filter_state.dropna()

In [28]:
noun_prhases_new_data_with_national_filter_state['Filter_ All'] = 1

In [29]:
noun_prhases_new_data_with_national_filter_state

Unnamed: 0     noun_sentence state   count      mean  variance  \
54909       54909            % usda    GA   464.0  0.019316  0.021405   
54911       54911               * *    GA  2667.0 -0.002018  0.052583   
54912       54912             * * *    GA  1618.0 -0.014187  0.048002   
54913       54913           * * * *    GA   292.0  0.004749  0.039338   
54936       54936  * stock photos *    GA  1941.0  0.004441  0.012156   
...           ...               ...   ...     ...       ...       ...   
65858       65858         year roof    GA   307.0  0.050504  0.019404   
65859       65859        year round    GA   390.0  0.052218  0.030751   
65865       65865     year warranty    GA   370.0  0.038584  0.030543   
65875       65875     you will fall    GA   347.0  0.067515  0.026877   
65885       65885       zoo atlanta    GA   235.0  0.006908  0.092656   

      noun_sentence_USA state_USA  count_USA  mean_USA  ...  \
54909            % usda       USA      954.0  0.013769  ...   
54911               * *       USA    34791.0 -0.005745  ...   
54912             * * *       USA    21454.0 -0.012814  ...   
54913           * * * *       USA     3334.0 -0.007703  ...   
54936  * stock photos *       USA     1941.0  0.004441  ...   
...                 ...       ...        ...       ...  ...   
65858         year roof       USA     5075.0  0.026951  ...   
65859        year round       USA     4150.0  0.020817  ...   
65865     year warranty       USA     6383.0  0.020940  ...   
65875     you will fall       USA     2702.0  0.027302  ...   
65885       zoo atlanta       USA      235.0  0.006908  ...   

       Filter_N100_Error1.5%_1.00_USA  Filter_N100_Error1.5%_0.50_USA  \
54909                               0                               0   
54911                               0                               0   
54912                               0                               0   
54913                               0                               0   
54936                               0                               0   
...                               ...                             ...   
65858                               0                               0   
65859                               0                               0   
65865                               0                               0   
65875                               0                               0   
65885                               0                               0   

       stdev/mean  Filter_N100_Error1.5%_state  \
54909    7.574387                            1   
54911  113.631850                            0   
54912   15.443595                            0   
54913   41.765901                            0   
54936   24.828825                            0   
...           ...                          ...   
65858    2.758166                            1   
65859    3.358241                            1   
65865    4.529428                            1   
65875    2.428263                            1   
65885   44.061308                            0   

       Filter_N100_Error1.5%_3.33_state  Filter_N100_Error1.5%_2.50_state  \
54909                                 0                                 0   
54911                                 0                                 0   
54912                                 0                                 0   
54913                                 0                                 0   
54936                                 0                                 0   
...                                 ...                               ...   
65858                                 1                                 0   
65859                                 0                                 0   
65865                                 0                                 0   
65875                                 1                                 1   
65885                                 0         

In [30]:
filter_df = noun_prhases_new_data_with_national_filter_state[\
            noun_prhases_new_data_with_national_filter_state.columns[\
            pd.Series(noun_prhases_new_data_with_national_filter_state.columns).str.startswith('Filter')]].sum().to_frame()

In [31]:
filter_df[filter_df.iloc[:,0]>30]

0
Filter_N100_Error1.5%_USA          954
Filter_N100_Error1.5%_3.33_USA     215
Filter_N100_Error1.5%_2.85_USA     156
Filter_N100_Error1.5%_2.50_USA     109
Filter_N100_Error1.5%_2.00_USA      46
Filter_N100_Error1.5%_state       1304
Filter_N100_Error1.5%_3.33_state   314
Filter_N100_Error1.5%_2.50_state   169
Filter_N100_Error1.5%_2.85_state   225
Filter_N100_Error1.5%_2.00_state    76
Filter_ All                       2207

In [32]:
filter_cases = ['Filter_ All', 'Filter_N100_Error1.5%_USA', 'Filter_N100_Error1.5%_3.33_USA',
               'Filter_N100_Error1.5%_2.85_USA', 'Filter_N100_Error1.5%_2.50_USA',
               'Filter_N100_Error1.5%_2.00_USA', 'Filter_N100_Error1.5%_state',
               'Filter_N100_Error1.5%_3.33_state', 'Filter_N100_Error1.5%_2.50_state',
               'Filter_N100_Error1.5%_2.85_state', 'Filter_N100_Error1.5%_2.00_state']

In [33]:
noun_prhases_new_data_with_national_filter_state_merged = \
                    noun_prhases_new_data_with_national_filter_state.merge(noun_sentence_state.loc[:,\
                                ['noun_sentence','AVM_Error_Average','Listing_Error_Average','AVM_Error_Indicators','Listing_Error_Indicators']],
                                how='left',left_on='noun_sentence', right_on='noun_sentence')

In [34]:
noun_prhases_new_data_with_national_filter_state_merged 

Unnamed: 0     noun_sentence state   count      mean  variance  \
0          54909            % usda    GA   464.0  0.019316  0.021405   
1          54911               * *    GA  2667.0 -0.002018  0.052583   
2          54912             * * *    GA  1618.0 -0.014187  0.048002   
3          54913           * * * *    GA   292.0  0.004749  0.039338   
4          54936  * stock photos *    GA  1941.0  0.004441  0.012156   
...          ...               ...   ...     ...       ...       ...   
2202       65858         year roof    GA   307.0  0.050504  0.019404   
2203       65859        year round    GA   390.0  0.052218  0.030751   
2204       65865     year warranty    GA   370.0  0.038584  0.030543   
2205       65875     you will fall    GA   347.0  0.067515  0.026877   
2206       65885       zoo atlanta    GA   235.0  0.006908  0.092656   

     noun_sentence_USA state_USA  count_USA  mean_USA  ...  \
0               % usda       USA      954.0  0.013769  ...   
1                  * *       USA    34791.0 -0.005745  ...   
2                * * *       USA    21454.0 -0.012814  ...   
3              * * * *       USA     3334.0 -0.007703  ...   
4     * stock photos *       USA     1941.0  0.004441  ...   
...                ...       ...        ...       ...  ...   
2202         year roof       USA     5075.0  0.026951  ...   
2203        year round       USA     4150.0  0.020817  ...   
2204     year warranty       USA     6383.0  0.020940  ...   
2205     you will fall       USA     2702.0  0.027302  ...   
2206       zoo atlanta       USA      235.0  0.006908  ...   

      Filter_N100_Error1.5%_3.33_state  Filter_N100_Error1.5%_2.50_state  \
0                                    0                                 0   
1                                    0                                 0   
2                                    0                                 0   
3                                    0                                 0   
4                                    0                                 0   
...                                ...                               ...   
2202                                 1                                 0   
2203                                 0                                 0   
2204                                 0                                 0   
2205                                 1                                 1   
2206                                 0                                 0   

      Filter_N100_Error1.5%_2.85_state  Filter_N100_Error1.5%_2.00_state  \
0                                    0                                 0   
1                                    0                                 0   
2                                    0                                 0   
3                                    0                                 0   
4                                    0                                 0   
...                                ...                               ...   
2202                                 1                                 0   
2203                                 0                                 0   
2204                                 0                                 0   
2205                                 1                                 0   
2206                                 0                                 0   

      Filter_N100_Error1.5%_1.00_state  Filter_ All  AVM_Error_Average  \
0                                    0            1           0.019316   
1                                    0            1          -0.002018   
2                                    0            1          -0.014187   
3                                    0            1           0.004749   
4                                    0            1           0.004441   
...                                ...          ...                ...   
2202                                 0            1 

In [35]:
columns_to_split = [ 'AVM_Error_Indicators', 'Listing_Error_Indicators']

In [36]:
for column in columns_to_split:
    nelements = (len(noun_prhases_new_data_with_national_filter_state_merged[column].values[0]))
    list_tmp = [str(i) for i in range(nelements)] 
    column_names = [column + '_' + str(i) for i in list_tmp] 
    print(column_names)
    split_df = pd.DataFrame(noun_prhases_new_data_with_national_filter_state_merged[column].tolist(), columns=column_names, 
                            index=noun_prhases_new_data_with_national_filter_state_merged.index)
    noun_prhases_new_data_with_national_filter_state_merged = pd.concat([noun_prhases_new_data_with_national_filter_state_merged, split_df], axis=1)
    noun_prhases_new_data_with_national_filter_state_merged = noun_prhases_new_data_with_national_filter_state_merged.drop(columns = [column])

['AVM_Error_Indicators_0', 'AVM_Error_Indicators_1', 'AVM_Error_Indicators_2', 'AVM_Error_Indicators_3', 'AVM_Error_Indicators_4', 'AVM_Error_Indicators_5', 'AVM_Error_Indicators_6', 'AVM_Error_Indicators_7', 'AVM_Error_Indicators_8', 'AVM_Error_Indicators_9', 'AVM_Error_Indicators_10', 'AVM_Error_Indicators_11']


TypeError: 'float' object is not iterable

In [62]:
noun_prhases_new_data_with_national_filter_state_merged[column].tolist()

[array([ 1.93156419e-02,  2.14049006e-02,  9.74722858e-01,  7.04842344e+00,
        -1.14569751e-01, -5.13988084e-02,  5.82469944e-03,  6.77144620e-02,
         1.73151282e-01,  4.64000000e+02,  5.17241379e+01,  4.82758621e+01]),
 array([-2.01801246e-03,  5.25833004e-02, -1.22457518e+01,  3.63226503e+02,
        -1.68126740e-01, -6.46856596e-02,  3.47826001e-03,  7.75822439e-02,
         1.68091224e-01,  2.66700000e+03,  5.17060367e+01,  4.82939633e+01]),
 array([-1.41866922e-02,  4.80019739e-02, -2.82760417e+00,  2.40432548e+01,
        -1.93731503e-01, -7.22749864e-02,  4.04323767e-03,  7.25274019e-02,
         1.63213150e-01,  1.61800000e+03,  5.10506799e+01,  4.89493201e+01]),
 array([ 4.74878852e-03,  3.93377375e-02, -2.34402797e+00,  1.06425613e+01,
        -1.37634309e-01, -4.33211890e-02,  3.24615602e-02,  9.25048855e-02,
         1.74965192e-01,  2.92000000e+02,  6.13013699e+01,  3.86986301e+01]),
 array([ 4.44066077e-03,  1.21564711e-02,  1.00708964e+00,  1.02954989e+01,
    

In [59]:
pd.DataFrame(noun_prhases_new_data_with_national_filter_state_merged['Listing_Error_Indicators'].values(), columns=column_names)

TypeError: 'numpy.ndarray' object is not callable

In [61]:
noun_prhases_new_data_with_national_filter_state_merged['Listing_Error_Indicators'].values

array([array([-1.59919194e-02,  2.36886481e-03, -1.20361483e+00,  3.95141243e+00,
       -8.03851034e-02, -3.62962963e-02,  0.00000000e+00,  7.46268657e-03,
        2.93388430e-02,  4.64000000e+02,  2.82327586e+01,  4.41810345e+01]),
       array([-2.47688521e-02,  5.95508416e-02, -2.94861093e+01,  9.96735399e+02,
       -1.01033127e-01, -4.47179011e-02,  0.00000000e+00,  1.99491714e-02,
        5.61156463e-02,  2.66700000e+03,  3.79077615e+01,  4.88938883e+01]),
       array([-1.82904399e-02,  9.32454519e-03, -1.26634228e-02,  2.84908561e+01,
       -1.11152279e-01, -4.60260672e-02, -1.99733471e-03,  2.32558140e-02,
        6.00000000e-02,  1.61800000e+03,  3.94313968e+01,  5.00618047e+01]),
       ...,
       array([-2.76695335e-02,  1.16017746e-02,  3.05034686e+00,  3.98850952e+01,
       -1.20326104e-01, -5.83486185e-02, -1.64177276e-02,  5.88235294e-04,
        3.46534653e-02,  3.70000000e+02,  2.72972973e+01,  5.72972973e+01]),
       nan,
       array([-1.46931535e-02,  1.751173

In [39]:
noun_prhases_new_data_with_national_filter_state_merged[column].tolist()

[array([ 1.93156419e-02,  2.14049006e-02,  9.74722858e-01,  7.04842344e+00,
        -1.14569751e-01, -5.13988084e-02,  5.82469944e-03,  6.77144620e-02,
         1.73151282e-01,  4.64000000e+02,  5.17241379e+01,  4.82758621e+01]),
 array([-2.01801246e-03,  5.25833004e-02, -1.22457518e+01,  3.63226503e+02,
        -1.68126740e-01, -6.46856596e-02,  3.47826001e-03,  7.75822439e-02,
         1.68091224e-01,  2.66700000e+03,  5.17060367e+01,  4.82939633e+01]),
 array([-1.41866922e-02,  4.80019739e-02, -2.82760417e+00,  2.40432548e+01,
        -1.93731503e-01, -7.22749864e-02,  4.04323767e-03,  7.25274019e-02,
         1.63213150e-01,  1.61800000e+03,  5.10506799e+01,  4.89493201e+01]),
 array([ 4.74878852e-03,  3.93377375e-02, -2.34402797e+00,  1.06425613e+01,
        -1.37634309e-01, -4.33211890e-02,  3.24615602e-02,  9.25048855e-02,
         1.74965192e-01,  2.92000000e+02,  6.13013699e+01,  3.86986301e+01]),
 array([ 4.44066077e-03,  1.21564711e-02,  1.00708964e+00,  1.02954989e+01,
    

In [ ]:
noun_sentence_state_test_transdate_train = noun_sentence_state_train.groupby('Transdate').mean()[['new_avmerror']].reset_index()
noun_sentence_state_test_transdate_train = noun_sentence_state_test_transdate_train.rename(columns={"new_avmerror": "avmerror_mean"})

In [ ]:
noun_sentence_state_test_transdate_test = noun_sentence_state_test.groupby('Transdate').mean()[['new_avmerror']].reset_index()
noun_sentence_state_test_transdate_test = noun_sentence_state_test_transdate_test.rename(columns={"new_avmerror": "avmerror_mean"})

In [ ]:
noun_sentence_state_train = noun_sentence_state_train.merge(noun_sentence_state_test_transdate_train,
                                                         how='left', left_on='Transdate', right_on='Transdate')

In [ ]:
noun_sentence_state_test = noun_sentence_state_test.merge(noun_sentence_state_test_transdate_test,
                                                         how='left', left_on='Transdate', right_on='Transdate')

In [ ]:

all_combinations = [['new_avmValue','cbsa'],
                    ['new_avmValue','cbsa', 'cj_living_area'],
                    ['new_avmValue','cbsa', 'cj_living_area', 'census_tract'],
                    ['new_avmValue','cbsa', 'cj_living_area', 'census_tract', 'Transdate'],
                    ['new_avmValue','cbsa', 'cj_living_area', 'census_tract',
                   'AVM_Error_Indicators_0', 'AVM_Error_Indicators_1',
                   'AVM_Error_Indicators_2', 'AVM_Error_Indicators_3',
                   'AVM_Error_Indicators_4', 'AVM_Error_Indicators_5',
                   'AVM_Error_Indicators_6', 'AVM_Error_Indicators_7',
                   'AVM_Error_Indicators_8', 'AVM_Error_Indicators_9',
                   'AVM_Error_Indicators_10', 'AVM_Error_Indicators_11',
                   'AVM_Error_Indicators_scale', 'AVM_Error_Indicators_scale_inverse',
                   'Listing_Error_Indicators_0', 'Listing_Error_Indicators_1',
                   'Listing_Error_Indicators_2', 'Listing_Error_Indicators_3',
                   'Listing_Error_Indicators_4', 'Listing_Error_Indicators_5',
                   'Listing_Error_Indicators_6', 'Listing_Error_Indicators_7',
                   'Listing_Error_Indicators_8', 'Listing_Error_Indicators_9',
                   'Listing_Error_Indicators_10', 'Listing_Error_Indicators_11',
                   'AVM_Error_Indicators_0_max_value',
                   'AVM_Error_Indicators_0_min_value',
                   'AVM_Error_Indicators_0_max_indicator',
                   'AVM_Error_Indicators_0_min_indicator',
                   'AVM_Error_Indicators_0_diff_indicator',
                   'AVM_Error_Indicators_0_diff_value', 'AVM_Error_Indicators_0_mean','avmerror_mean'] +\
                    list(noun_sentence_state_train.columns[51:-3]),
                   ['new_avmValue','cbsa', 'cj_living_area',
                   'AVM_Error_Indicators_0', 'AVM_Error_Indicators_1',
                   'AVM_Error_Indicators_2', 'AVM_Error_Indicators_3',
                   'AVM_Error_Indicators_4', 'AVM_Error_Indicators_5',
                   'AVM_Error_Indicators_6', 'AVM_Error_Indicators_7',
                   'AVM_Error_Indicators_8', 'AVM_Error_Indicators_9',
                   'AVM_Error_Indicators_10', 'AVM_Error_Indicators_11',
                   'AVM_Error_Indicators_scale', 'AVM_Error_Indicators_scale_inverse',
                   'Listing_Error_Indicators_0', 'Listing_Error_Indicators_1',
                   'Listing_Error_Indicators_2', 'Listing_Error_Indicators_3',
                   'Listing_Error_Indicators_4', 'Listing_Error_Indicators_5',
                   'Listing_Error_Indicators_6', 'Listing_Error_Indicators_7',
                   'Listing_Error_Indicators_8', 'Listing_Error_Indicators_9',
                   'Listing_Error_Indicators_10', 'Listing_Error_Indicators_11',
                   'AVM_Error_Indicators_0_max_value',
                   'AVM_Error_Indicators_0_min_value',
                   'AVM_Error_Indicators_0_max_indicator',
                   'AVM_Error_Indicators_0_min_indicator',
                   'AVM_Error_Indicators_0_diff_indicator',
                   'AVM_Error_Indicators_0_diff_value', 'AVM_Error_Indicators_0_mean','avmerror_mean'] +\
                    list(noun_sentence_state_train.columns[51:-3]),
                   ['new_avmValue','cbsa', 'cj_living_area', 'Transdate', 
                   'AVM_Error_Indicators_0', 'AVM_Error_Indicators_1',
                   'AVM_Error_Indicators_2', 'AVM_Error_Indicators_3',
                   'AVM_Error_Indicators_4', 'AVM_Error_Indicators_5',
                   'AVM_Error_Indicators_6', 'AVM_Error_Indicators_7',
                   'AVM_Error_Indicators_8', 'AVM_Error_Indicators_9',
                   'AVM_Error_Indicators_10', 'AVM_Error_Indicators_11',
                   'AVM_Error_Indicators_scale', 'AVM_Error_Indicators_scale_inverse',
                   'Listing_Error_Indicators_0', 'Listing_Error_Indicators_1',
                   'Listing_Error_Indicators_2', 'Listing_Error_Indicators_3',
                   'Listing_Error_Indicators_4', 'Listing_Error_Indicators_5',
                   'Listing_Error_Indicators_6', 'Listing_Error_Indicators_7',
                   'Listing_Error_Indicators_8', 'Listing_Error_Indicators_9',
                   'Listing_Error_Indicators_10', 'Listing_Error_Indicators_11',
                   'AVM_Error_Indicators_0_max_value',
                   'AVM_Error_Indicators_0_min_value',
                   'AVM_Error_Indicators_0_max_indicator',
                   'AVM_Error_Indicators_0_min_indicator',
                   'AVM_Error_Indicators_0_diff_indicator',
                   'AVM_Error_Indicators_0_diff_value', 'AVM_Error_Indicators_0_mean','avmerror_mean'] +\
                    list(noun_sentence_state_train.columns[51:-3]),
                   ['new_avmValue','cbsa', 'cj_living_area', 'census_tract', 'Transdate', 
                   'AVM_Error_Indicators_0', 'AVM_Error_Indicators_1',
                   'AVM_Error_Indicators_2', 'AVM_Error_Indicators_3',
                   'AVM_Error_Indicators_4', 'AVM_Error_Indicators_5',
                   'AVM_Error_Indicators_6', 'AVM_Error_Indicators_7',
                   'AVM_Error_Indicators_8', 'AVM_Error_Indicators_9',
                   'AVM_Error_Indicators_10', 'AVM_Error_Indicators_11',
                   'AVM_Error_Indicators_scale', 'AVM_Error_Indicators_scale_inverse',
                   'Listing_Error_Indicators_0', 'Listing_Error_Indicators_1',
                   'Listing_Error_Indicators_2', 'Listing_Error_Indicators_3',
                   'Listing_Error_Indicators_4', 'Listing_Error_Indicators_5',
                   'Listing_Error_Indicators_6', 'Listing_Error_Indicators_7',
                   'Listing_Error_Indicators_8', 'Listing_Error_Indicators_9',
                   'Listing_Error_Indicators_10', 'Listing_Error_Indicators_11',
                   'AVM_Error_Indicators_0_max_value',
                   'AVM_Error_Indicators_0_min_value',
                   'AVM_Error_Indicators_0_max_indicator',
                   'AVM_Error_Indicators_0_min_indicator',
                   'AVM_Error_Indicators_0_diff_indicator',
                   'AVM_Error_Indicators_0_diff_value', 'AVM_Error_Indicators_0_mean','avmerror_mean'] +\
                    list(noun_sentence_state_train.columns[51:-3])]

In [ ]:
list(noun_sentence_state_train.columns[51:-3])[-1]

In [ ]:
all_combinations_names = ['new_avmValue-cbsa', 
                          'new_avmValue-cbsa-cj_living_area',
                          'new_avmValue-cbsa-cj_living_area-census_tract',
                          'new_avmValue-cbsa-cj_living_area-census_tract-Transdate',
                          'new_avmValue-cbsa-cj_living_area-census_tract-comments',
                          'new_avmValue-cbsa-cj_living_area-comments',
                          'new_avmValue-cbsa-cj_living_area-comments-Transdate',
                          'new_avmValue-cbsa-cj_living_area-comments-census_tract-Transdate']

In [ ]:
from lightgbm import LGBMRegressor

In [ ]:
for idd,list_preds in enumerate(all_combinations):
    #print(list(list_preds))
    print(all_combinations_names[idd])
    
    selcted_columns = list_preds
    symptoms_df = noun_sentence_state_train.loc[:,selcted_columns]
    symptoms_df_test = noun_sentence_state_test.loc[:,selcted_columns]
    
    Predictors = symptoms_df.to_numpy()
    X_test = symptoms_df_test.to_numpy()
    X_train = Predictors

    y_train_regressor = noun_sentence_state_train.new_avmerror.values
    y_test_regressor = noun_sentence_state_test.new_avmerror.values
    
    model_regressor = LGBMRegressor(max_depth = 10, n_estimators = 150, num_leaves = 700, colsample_bytree=0.4) 
    model_regressor.fit(X_train, y_train_regressor)
    
    predictions_train_Regressor = model_regressor.predict(X_train)
    predictions_test_Regressor = model_regressor.predict(X_test)

    
    avmValue_test = noun_sentence_state_test['new_avmValue']
    avmValue_train = noun_sentence_state_train['new_avmValue']

    transprice_test = noun_sentence_state_test['Transprice']
    transprice_train = noun_sentence_state_train['Transprice']

    predictions_test_valueR = avmValue_test/(1-predictions_test_Regressor)
    predictions_train_valueR = avmValue_train/(1-predictions_train_Regressor)
    
    
    print('') 
    print('Testing')
    print(np.mean(np.abs(transprice_test-predictions_test_valueR)/\
              (transprice_test)))
    print(np.mean(np.abs(transprice_test - avmValue_test)/\
                  (transprice_test)))

    print('') 
    print('Training') 
    print(np.mean(np.abs(transprice_train-predictions_train_valueR)/\
              (transprice_train)))
    print(np.mean(np.abs(transprice_train - avmValue_train)/\
                  (transprice_train)))   
    
    import joblib
    filename = 'LGBM_regressor_additive_'+state+'_'+str(idd)+'_new_avm.sav'
    joblib.dump(model_regressor,filename)
    print(' ')
    